export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_INFO_PENDING = 'REQUEST_INFO_PENDING'
export const REQUEST_INFO_SUCCESS = 'REQUEST_INFO_SUCCESS'
export const REQUEST_INFO_FAILED = 'REQUEST_INFO_FAILED'